#!/usr/bin/env bash

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim"

# Friendlier copy commands for xclip if present
[ -x "$(command -v xclip)" ] && alias \
    pbcopy="xclip -selection c" \
    pbpaste="xclip -o -selection c"

# Verbosity
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -Iv"

# Colorize commands when possible.
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto"

# Shorter commands
alias \
    open="xdg-open" \
    tree="tree --dirsfirst -C -a -I '.git|.venv|*cache*|target'"
